models/posts.py
from dataclasses import dataclass
from datetime import datetime
# Internal packages
from flask_base import db


@dataclass
class Posts(db.Model):
    id: int
    lang: str
    title: str
    date_posted: datetime
    content: str
    user_id: int

    id = db.Column(db.Integer, primary_key=True)
    lang = db.Column(db.String(2), nullable=False)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Posts('{self.title}', '{self.date_posted}')"

forms/posts.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    lang = SelectField('Language', validators=[DataRequired()], choices=['en', 'et'])
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

routes/admin.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
# Internal packages
from flask_base import db
from models import Posts, get_model_by_tablename
from forms import PostForm

admin = Blueprint('admin', __name__)


@admin.route('/admin')
@login_required
def tables() -> str:
    """Main blog"""
    # Render buttons to tables
    tbls = db.metadata.tables.keys()
    return render_template('account/admin.html', tables=tbls, title='Admin')


@admin.route('/admin/tbl/<string:tbl_name>')
@login_required
def render_table(tbl_name: str):
    page = request.args.get('page', 1, type=int)
    if tbl_name in db.metadata.tables.keys():
        # Begin rendering table
        model = get_model_by_tablename(db, tbl_name)
        results = model.query.paginate(page=page, per_page=20)
        return render_template('account/admin_table.html', results=results)
    else:
        flash(f'Table {tbl_name} not found. Please check the name and try again.', 'alert-danger')

routes/main.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def index():
    return render_template('index.html')


@main.route('/about')
def about():
    return render_template('about.html', title='About')


@main.route('/cv')
def cv():
    return render_template('cv.html', title='CV')


@main.route('/projects')
def projects():
    return render_template('projects.html', title='Projects')


@main.route('/contact')
def contact() -> str:
    return render_template('contact.html', title='Contact')

routes/posts.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
# Internal packages
from flask_base import db
from models import Posts
from forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/blog')
def blog() -> str:
    """Main blog"""
    page = request.args.get('page', 1, type=int)
    posts_to_fetch = Posts.query.order_by(Posts.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('blog.html', posts=posts_to_fetch, title='Blog')


@posts.route("/blog/<int:post_id>")
def post(post_id: float):
    """Loads specific blog post by ID"""
    post_to_fetch = Posts.query.get_or_404(post_id)
    return render_template('blog/post.html', title=post_to_fetch.title, post=post_to_fetch)


@posts.route("/blog/new", methods=('GET', 'POST'))
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post_data = Posts(lang=form.lang.data, title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post_data)
        db.session.commit()
        flash('Your post has been created!', 'alert-success')
        return redirect(url_for('posts.post', post_id=post_data.id))
    return render_template('blog/create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/blog/<int:post_id>/update", methods=('GET', 'POST'))
@login_required
def update_post(post_id: float):
    post_to_update = Posts.query.get_or_404(post_id)
    if post_to_update.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post_to_update.title = form.title.data
        post_to_update.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'alert-success')
        return redirect(url_for('posts.post', post_id=post_to_update.id))
    elif request.method == 'GET':
        form.title.data = post_to_update.title
        form.content.data = post_to_update.content
    return render_template('blog/create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/blog/<int:post_id>/delete", methods=('POST',))
@login_required
def delete_post(post_id: float) -> str:
    post_to_delete = Posts.query.get_or_404(post_id)
    if post_to_delete.author != current_user:
        abort(403)
    db.session.delete(post_to_delete)
    db.session.commit()
    flash('Your post has been deleted!', 'alert-success')
    return redirect(url_for('posts.blog'))

routes/user.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
# Internal packages
from flask_base import db, bcrypt
from models import User, Posts
from forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordForm

users = Blueprint('users', __name__)


@users.route("/register", methods=('GET', 'POST'))
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'alert-success')
        return redirect(url_for('users.login'))
    return render_template('account/register.html', title='Register', form=form)


@users.route("/login", methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'alert-danger')
    return render_template('account/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/account", methods=('GET', 'POST'))
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        db.session.commit()
        flash('Your account has been updated!', 'alert-success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
    return render_template('account/account.html', title='Account', form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Posts.query.filter_by(author=user)\
        .order_by(Posts.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('blog/user_posts.html', posts=posts, user=user)


@users.route("/reset_password/<token>", methods=('GET', 'POST'))
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'alert-warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'alert-success')
        return redirect(url_for('users.login'))
    return render_template('account/reset_token.html', title='Reset Password', form=form)

templates/_post.html
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      {% if post.author == current_user %}
        <div>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
          <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
      {% endif %}
    </div>
    <a class="link" href="{{ url_for('posts.post', post_id=post.id) }}"><h2 class="article-title">{{ post.title }}</h2></a>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">{{ _('Delete Post?') }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ _('Close') }}</button>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>

templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1></h1>
{% endblock %}

templates/account.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-section">
      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ _('Account Info') }}</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/png">
    <!-- CSS -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <!-- JS -->
    <!-- FontAwesome -->
    <script src="https://use.fontawesome.com/9b3bd4052a.js"></script>
    {% if title %}
        <title>bobrock.dev - {{ title }}</title>
    {% else %}
        <title>bobrock.dev</title>
    {% endif %}
  </head>
  <body>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">
            <img class="nav-logo" src="{{ url_for('static', filename='images/favicon.png') }}" alt="20-sided die logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                {% set nav_dict = [
                    ('posts.blog', 'Blog'),
                    ('main.projects', 'Projects'),
                    ('main.contact', 'Contact')
                ] -%}

                {% for id, caption in nav_dict %}
                    <li class="nav-item {{'active' if request.endpoint == id}}">
                        <a class="nav-link" href="{{ url_for(id) }}">{{ caption }}</a>
                    </li>
                {% endfor %}
            </ul>
             <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    {% if request.endpoint in ['posts.blog', 'posts.post'] %}
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                    {% endif %}
                    <a class="nav-item nav-link" href="{{ url_for('admin.tables') }}">Admin</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert {{ category }}"> {{ message|capitalize }} </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %} {% endblock %}
    </div>
    <div id="content">

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <h1></h1>
{% endblock %}

templates/create_post.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.lang.label(class="form-control-label") }}
                {% if form.lang.errors %}
                    {{ form.lang(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.lang.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.lang(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg", data_editor="markdown") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/ace/1.1.3/ace.js"></script>
    <script type="text/javascript">
        // https://gist.github.com/duncansmart/5267653
        // find each text area marked to have an editor
        $('textarea[data-editor]').each(function() {
            var textarea = $(this);
            var mode = textarea.data('editor');
            // create the editor div
            var div = $('<div>', {
                'width': textarea.outerWidth(),
                'height': textarea.outerHeight(),
                'class': textarea.attr('class')
            }).insertBefore(textarea);
            // hide the original text area
            textarea.hide();
            // configure the editor
            var editor = ace.edit(div[0]);
            var session = editor.getSession();
            editor.setTheme("ace/theme/github");
            session.setValue(textarea.val());
            session.setMode('ace/mode/' + mode);
            session.setNewLineMode('unix');
            session.setTabSize(4);
            session.setUseSoftTabs(true);
            session.setUseWrapMode(true);
            // update the text area before submitting the form
            textarea.closest('form').submit(function() {
                textarea.val(editor.getSession().getValue());
            });
        });
    </script>
</div>
{% endblock content %}

templates/cv.html
{% extends 'base.html' %}

{% block content %}
    <h1></h1>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h2>Personal Website.</h2>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ _('Log In') }}</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">{{ _('Forgot Password?')}}</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            {{ _('Need An Account?') }}
            <a class="ml-2" href="{{ url_for('users.register') }}">{{ _('Sign Up Now') }}</a>
        </small>
    </div>
{% endblock content %}

templates/post.html
{% extends 'base.html' %}
{% block content %}
  {% include '_post.html' %}
{% endblock content %}

templates/projects.html
{% extends 'base.html' %}

{% block content %}
    <h1></h1>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ _('Join Today') }}</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.control.label(class="form-control-label") }}
                    {% if form.control.errors %}
                        {{ form.control(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.control.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.control(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            {{ _('Already Have An Account?') }}
            <a class="ml-2" href="{{ url_for('users.login') }}">{{ _('Sign In') }}</a>
        </small>
    </div>
{% endblock content %}

templates/reset_token.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ _('Reset Password') }}</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

templates/user_posts.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="mb-3">{{ _('Posts by %(username)s', username=user.username) }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}